HOSTS:
  ubuntu-1404-x64:
    roles:
      - master
      - database
      - dashboard
      - agent
      - appserver
      - dmgr
      - ihs
    platform: ubuntu-14.04-amd64
    pe_ver: http://enterprise.delivery.puppetlabs.net/2018.1/ci-ready/LATEST
    pe_dir: http://enterprise.delivery.puppetlabs.net/2018.1/ci-ready
    hypervisor: docker
    image: ubuntu:14.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      # ensure that upstart is booting correctly in the container
      - 'rm /usr/sbin/policy-rc.d && rm /sbin/initctl && dpkg-divert --rename --remove /sbin/initctl && apt-get update && apt-get install -y net-tools wget && locale-gen en_US.UTF-8'
CONFIG:
  trace_limit: 200
