---
".gitlab-ci.yml":
  delete: true
.pdkignore:
  paths:
    - /plans/provision_machines.pp
    - /plans/pe_server_setup.pp
    - /plans/puppet_agents_setup.pp
".rubocop.yml":
  default_configs:
    inherit_from: ".rubocop_todo.yml"
appveyor.yml:
  delete: true

Gemfile:
  optional:
    ":development":
      - gem: github_changelog_generator
      - gem: master_manipulator
    ":system_tests":
      - gem: master_manipulator
Rakefile:
  extras:
    - |
      require 'rspec/core/rake_task'
      namespace :websphere_application_server do
        RSpec::Core::RakeTask.new(:integration) do |t|
          t.pattern = 'spec/acceptance/**{,/*/**}/*_spec.rb'
          t.rspec_opts = "--tag integration"
        end
      end

spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
