HOSTS:
  unytaasg2gwn95n.delivery.puppetlabs.net:
    roles:
      - master
      - database
      - dashboard
      - agent
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
  gc6md5s4il1ox76.delivery.puppetlabs.net:
    roles:
      - agent
      - appserver
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
  ecr9qryi7eeo0jm.delivery.puppetlabs.net:
    roles:
      - agent
      - dmgr
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
  ehvh64hm7dcf8ow.delivery.puppetlabs.net:
    roles:
      - agent
      - ihs
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
CONFIG:
  nfs_server: none
  consoleport: 443
  datastore: instance0
  folder: Delivery/Quality Assurance/Enterprise/Dynamic
  resourcepool: delivery/Quality Assurance/Enterprise/Dynamic
  pooling_api: http://vcloud.delivery.puppetlabs.net/
