HOSTS:
  u9e8qf6cejxpe8h.delivery.puppetlabs.net:
    roles:
      - master
      - database
      - dashboard
      - agent
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
  hoafqikwkxbdbci.delivery.puppetlabs.net:
    roles:
      - agent
      - appserver
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
  q5kvgoq4n0d3ibx.delivery.puppetlabs.net:
    roles:
      - agent
      - dmgr
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
  gg149pb8ommw7xb.delivery.puppetlabs.net:
    roles:
      - agent
      - ihs
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
CONFIG:
  nfs_server: none
  consoleport: 443
  datastore: instance0
  folder: Delivery/Quality Assurance/Enterprise/Dynamic
  resourcepool: delivery/Quality Assurance/Enterprise/Dynamic
  pooling_api: http://vcloud.delivery.puppetlabs.net/
