HOSTS:
  t3qzazeynk0vg47.delivery.puppetlabs.net:
    roles:
      - master
      - database
      - dashboard
      - agent
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
  kud0nnzbc0bxb6m.delivery.puppetlabs.net:
    roles:
      - agent
      - appserver
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
  hrv93fb07svuoas.delivery.puppetlabs.net:
    roles:
      - agent
      - dmgr
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
  geg7ha9n0whfosy.delivery.puppetlabs.net:
    roles:
      - agent
      - ihs
    platform: el-6-x86_64
    template: Delivery/Quality Assurance/Templates/vCloud/centos-6-x86_64
    hypervisor: vcloud
CONFIG:
  nfs_server: none
  consoleport: 443
  datastore: instance0
  folder: Delivery/Quality Assurance/Enterprise/Dynamic
  resourcepool: delivery/Quality Assurance/Enterprise/Dynamic
  pooling_api: http://vcloud.delivery.puppetlabs.net/
